//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKP_ZKI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int id_answer { get; set; }
        public string Answer { get; set; }
        public Nullable<int> id_question { get; set; }
        public Nullable<int> id_text { get; set; }
    
        public virtual Questions Questions { get; set; }
        public virtual Texts Texts { get; set; }
    }
}
